general {
	output_format = "i3bar"
	colors = true
	interval = 5
}

order += "cpu_temperature 0"
order += "volume master"
order += "battery 0"
order += "memory"
order += "tztime local"
order += "ethernet eth0"
order += "wireless wlo1"

wireless wlo1 {
        format_up = "W: (%quality at %essid, %bitrate) %ip"
        format_down = "W: down"
}

ethernet enp4s0 {
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}

cpu_temperature 0 {
        format = "T: %degrees °C"
        path = "/sys/class/thermal/thermal_zone0/temp"
}

volume master {
   format = "♪: %volume"
   format_muted = "♪: muted (%volume)"
   device = "default"
   mixer = "Master"
   mixer_idx = 0
}

battery 0 {
    format = "%status %percentage %remaining %emptytime"
    format_down = "No Battery"
    status_chr = "⚡ CHR"
    status_bat = "🔋 BAT"
    status_unk = "? UNK"
    status_full = "☻ FULL"
    status_idle = "☻ IDLE"
    path = "/sys/class/power_supply/BAT1/uevent"
    low_threshold = 10
    integer_battery_capacity = true
}

tztime local {
        format = "%Y-%m-%d %H:%M:%S"
}

memory {
        format = "FREE: %free | USED : %used | TOTAL: %total"
        threshold_degraded = "10%"
        format_degraded = "MEMORY: %free"
}
